export const GET_APPLIANCES = 'GET_APPLIANCES';
export const GET_ROOMS = 'GET_ROOMS';
export const CHANGE_APPLIANCES = 'CHANGE_APPLIANCES';
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const EDIT_APPLIANCES = 'EDIT_APPLIANCES';
export const ADD_APPLIANCES = 'ADD_APPLIANCES';
export const DELETE_APPLIANCES = 'DELETE_APPLIANCES';
